In [1]:
import os
import sys
sys.path.append('/Users/mariana/Documents/projects/Huawei/survan')
# sys.path.append('/home/mvargas/code/Huawei/survan')

from deep_lambda_cox import DeepLambdaSA
from lambda_cox import LambdaSA
from baseline_cox import SA
from utils import concordance_index

import yaml
import jax
import jax.numpy as jnp
import numpy as np
import pickle

In [2]:
root_pth = '/Users/mariana/Documents/projects/Huawei/Results/with_landmark/'
config_path = os.path.join(root_pth, 'config.yaml')
config = yaml.load(open(config_path, 'r'), Loader=yaml.FullLoader)

config['dataset_kwargs']['data_path'] = '/Users/mariana/Documents/projects/Huawei/SurvanData/mixed_tasks/mixed/H_100/dataset.h5'

In [3]:
model_path = os.path.join(root_pth, 'mixed_tasks/seed_1/model.pt')

In [32]:
model = DeepLambdaSA(config, seed=1)

In [5]:
params = pickle.load(open(model_path, 'rb'))

In [6]:
model.state = model.state.replace(params=params)

In [33]:
train_gen, test_gen = model.get_train_test()
seqs = test_gen.X
ts = test_gen.ts
cs = test_gen.cs

In [8]:
surv = model.survival_curve(seqs)
bs = model.integrated_brier_score(surv[:,0], ts, cs)
beta = model.state.params['cox_linear_model']['beta']
scores = model.scores(jnp.expand_dims(seqs[:,0], axis=1)).squeeze()
ci = concordance_index(scores, ts, cs)

In [9]:
bs

Array(0.05729952, dtype=float32)

In [10]:
ci

0.9247260674699849

In [34]:
seqs == prev

Array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  Tr

In [24]:
prev = jnp.copy(seqs)

In [12]:
train_gen.X.shape

(18054, 100, 39)

In [13]:
train_gen.X[19]

array([[0.990099  , 0.68531793, 0.6715005 , ..., 0.49427783, 0.5963959 ,
        0.5763146 ],
       [0.9933993 , 0.57370293, 0.58468735, ..., 0.45408675, 0.5285764 ,
        0.51355225],
       [0.9966997 , 0.07756153, 0.07959719, ..., 0.05140931, 0.06823289,
        0.06737795],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], dtype=float32)

In [17]:
train_gen.y[19][:10,:10]

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [22]:
train_gen.h_ws[19][:10,:10]

array([[1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [23]:
train_gen.cs[19]

False